version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Asia/Tokyo"
    groups:
      major:
        update-types:
          - "major"
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      # Avoid default day of week because of potential rush.
      day: "tuesday"
      time: "12:00"
      timezone: "Asia/Tokyo"
    groups:
      all:
        patterns:
          - "*"

