name: "Setup gitleaks"
description: "Setup gitleaks"
runs:
  using: "composite"
  steps:
    - name: Setup gitleaks
      env:
        TARGET: linux_x64
        VERSION: 8.23.3
        # From https://github.com/gitleaks/gitleaks/releases/
        SHA256_SUM: 73a35edc2285afd689e712b8e0ebad3f2eaf94b0d67cd6e1f0ec693ac751bb4a
      # Explicitly specifing `bash` changes behavior: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
      shell: bash
      run: |
        set -x
        curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
          --location --remote-name \
          "https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_${TARGET}.tar.gz"
        echo "${SHA256_SUM} gitleaks_${VERSION}_${TARGET}.tar.gz" | sha256sum --check
        # Generate `gitleaks` binary
        tar --extract --gzip --file "gitleaks_${VERSION}_${TARGET}.tar.gz" --verbose
        sudo install gitleaks /usr/local/bin/gitleaks
