name: "Setup gitleaks"
runs:
  using: "composite"
  steps:
    - name: Setup gitleaks
      env:
        TARGET: linux_amd64
        VERSION: 8.18.1-patch1
        # From https://github.com/taiki45/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_checksums.txt
        SHA256_SUM: aed536718ac444b6727754ca2e34e243ec1aee8bce928975233709d57bc61387
      # Explicitly specifing `bash` changes behavior: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
      shell: bash
      run: |
        set -x
        curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
          --location --remote-name \
          "https://github.com/taiki45/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_${TARGET}.tar.gz"
        echo "${SHA256_SUM} gitleaks_${VERSION}_${TARGET}.tar.gz" | sha256sum --check
        # Generate `gitleaks` binary
        tar --extract --gzip --file "gitleaks_${VERSION}_${TARGET}.tar.gz" --verbose
        sudo install gitleaks /usr/local/bin/gitleaks
