name: clippy-action
on: [pull_request]
jobs:
  clippy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # No semver tag.
      with:
        toolchain: stable
        components: clippy
    - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
    - uses: giraffate/clippy-action@13b9d32482f25d29ead141b79e7e04e7900281e0 # v1.0.1
      with:
        reporter: 'github-pr-check'
        github_token: ${{ secrets.GITHUB_TOKEN }}
