name: Test GitHub annotation

on: pull_request

jobs:
  test-github-annotation:
    name: Test GitHub annotation
    runs-on: ubuntu-latest
    steps:
      - name: Setup gitleaks
        env:
          TARGET: linux_amd64
          VERSION: 8.18.1-patch1
          # From https://github.com/taiki45/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_checksums.txt
          SHA256_SUM: aed536718ac444b6727754ca2e34e243ec1aee8bce928975233709d57bc61387
        # Explicitly specifing `bash` changes behavior: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
        shell: bash
        run: |
          set -x
          curl --silent --show-error --fail --connect-timeout 3 --max-time 10 --retry 3 \
            --location --remote-name \
            "https://github.com/taiki45/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_${TARGET}.tar.gz"
          echo "${SHA256_SUM} gitleaks_${VERSION}_${TARGET}.tar.gz" | sha256sum --check
          # Generate `gitleaks` binary
          tar --extract --gzip --file "gitleaks_${VERSION}_${TARGET}.tar.gz" --verbose
          sudo install gitleaks /usr/local/bin/gitleaks
      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248 # Latest as of 2023-11-16
        with:
          toolchain: stable
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
        with:
          reviewdog_version: latest
      - name: Test apply
        env:
          REPORT_PATH: tmp/report.json
          GUIDE: "see more detail at https://example.com"
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        # Test data: secret_key = deadbeef
        run: |
          set -x
          mkdir -p tmp
          gitleaks detect --verbose --exit-code=0 --no-banner --config=tests/testdata/scan_config.toml --report-path="${REPORT_PATH}"
          cargo run apply --no-fail --format=sarif --config-path=tests/testdata/empty_allowlist.toml | \
            reviewdog -f=sarif -reporter=github-pr-check -level=warning -name=gls
